# Generated by Django 3.1.11 on 2021-09-21 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.TextField(blank=True, default=None, max_length=10000, null=True)),
                ('title', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('maximum_grade', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('penalty_type', models.IntegerField(default=0)),
                ('maximum_attempts', models.IntegerField(blank=True, default=-1)),
                ('other_marking_criteria', models.TextField(blank=True, max_length=1000)),
                ('custom_css', models.TextField(blank=True, max_length=1000)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField(blank=True, max_length=1000)),
                ('ip_address', models.GenericIPAddressField(null=True)),
                ('mark', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('total', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('penalty_type', models.IntegerField(default=0)),
                ('attempt_number', models.IntegerField(default=None)),
                ('regression_penalty', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('previous_mark', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('feedback', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('marker_feedback', models.TextField(blank=True, default=None, max_length=1000, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=300000)),
                ('marking_code', models.TextField(blank=True, max_length=300000)),
                ('marker_page', models.TextField(blank=True, max_length=300000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.questiontype')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='question_template',
            field=models.ForeignKey(default='8', on_delete=django.db.models.deletion.PROTECT, to='questions.questiontemplate'),
        ),
        migrations.CreateModel(
            name='PotentialAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, max_length=1000)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potential_answers', to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQuestionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('maximum_grade', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('generation_code', models.TextField(blank=True, max_length=300000)),
                ('question_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.questiontemplate')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedQuestionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('question_seed', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('question_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.generatedquestiontype')),
            ],
        ),
    ]
